# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-02 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('movie_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='电影编号')),
                ('movie_title', models.CharField(max_length=100, verbose_name='电影名称')),
                ('movie_type', models.CharField(default='#', max_length=50, verbose_name='电影类型')),
                ('movie_ctr', models.CharField(default='#', max_length=20, verbose_name='制片国家')),
                ('movie_lan', models.CharField(default='#', max_length=20, verbose_name='语言')),
                ('movie_date', models.CharField(default='#', max_length=30, verbose_name='上映日期')),
                ('movie_time', models.CharField(default='#', max_length=10, verbose_name='片长')),
                ('movie_intro', models.TextField(default='#', verbose_name='剧情简介')),
                ('movie_pic', models.CharField(default='#', max_length=150, verbose_name='图片链接')),
                ('movie_dir', models.CharField(default='#', max_length=30, verbose_name='导演')),
                ('movie_big_pic', models.CharField(default='#', max_length=150, verbose_name='大图')),
            ],
        ),
    ]
