# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-04-02 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('movie_id', models.CharField(max_length=20)),
                ('ratings', models.IntegerField()),
                ('timestamp', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ItemRec',
            fields=[
                ('movie_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('item_rec', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('psw', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserRec',
            fields=[
                ('user_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_rec', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='UserRecords',
            fields=[
                ('records', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('user_id', models.CharField(default='#', max_length=10)),
                ('click_date', models.CharField(default='#', max_length=10)),
                ('click_movie', models.CharField(default='#', max_length=10)),
                ('interest', models.CharField(default='#', max_length=2)),
                ('click_times', models.CharField(default='#', max_length=2)),
            ],
        ),
    ]
